[package]
name = "rustnotepad_printing"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
image = { version = "0.24", default-features = false, features = ["png"] }

[dev-dependencies]
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
