[package]
name = "rustnotepad_project"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
serde_json = "1.0"
